# Generated by Django 2.0.2 on 2018-02-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentanalysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Output_Table',
            new_name='Results',
        ),
    ]
