# Generated by Django 2.0.2 on 2018-02-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentanalysis', '0002_auto_20180221_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
