# Generated by Django 2.0.2 on 2018-02-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentanalysis', '0003_auto_20180221_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='ASIN',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
